routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\JournalsController::class, 'index'])->name('main');

Route::group(['namespace' => 'Journals', 'prefix' => 'journals'], function(){
    Route::get('/', [\App\Http\Controllers\JournalsController::class, 'index'])->name('journals');
    Route::get('/create', [\App\Http\Controllers\JournalsController::class, 'create'])->name('journals.create');
    Route::post('/', [\App\Http\Controllers\JournalsController::class, 'store'])->name('journals.store');
    Route::get('/{journal}', [\App\Http\Controllers\JournalsController::class, 'show'])->name('journals.show');
    Route::get('/edit/{journal}', [\App\Http\Controllers\JournalsController::class, 'edit'])->name('journals.edit');
    Route::patch('/{journal}', [\App\Http\Controllers\JournalsController::class, 'update'])->name('journals.update');
    Route::delete('/{journal}', [\App\Http\Controllers\JournalsController::class, 'delete'])->name('journals.delete');
    Route::post('/fetch_data', [\App\Http\Controllers\JournalsController::class, 'fetchData'])->name('journals.fetch_data');
});

Route::group(['namespace' => 'Authors', 'prefix' => 'authors'], function(){
    Route::get('/', [\App\Http\Controllers\AuthorsController::class, 'index'])->name('authors');
    Route::get('/create', [\App\Http\Controllers\AuthorsController::class, 'create'])->name('authors.create');
    Route::post('/', [\App\Http\Controllers\AuthorsController::class, 'store'])->name('authors.store');
    Route::get('/{author}', [\App\Http\Controllers\AuthorsController::class, 'show'])->name('authors.show');
    Route::get('/edit/{author}', [\App\Http\Controllers\AuthorsController::class, 'edit'])->name('authors.edit');
    Route::patch('/{author}', [\App\Http\Controllers\AuthorsController::class, 'update'])->name('authors.update');
    Route::delete('/{author}', [\App\Http\Controllers\AuthorsController::class, 'delete'])->name('authors.delete');
    Route::get('/{author}/journals', [\App\Http\Controllers\AuthorsController::class, 'journals'])->name('authors.journals');
    Route::post('/fetch_data', [\App\Http\Controllers\AuthorsController::class, 'fetchData'])->name('authors.fetch_data');
});

app/Models/Author.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Author extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'authors';
    protected $guarded = false;
    protected $fillable = [
        'lastname',
        'firstname',
        'secondname',
    ];

    public function journals()
    {
        return $this->belongsToMany(Journal::class, 'journal_authors', 'author_id', 'journal_id');
    }
}

app/Models/Journal.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon\Carbon;

class Journal extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'journals';
    protected $guarded = false;
    protected $fillable = [
        'title',
        'description',
    ];

    public function images()
    {
        return $this->hasMany(Image::class);
    }

    public function authors()
    {
        return $this->belongsToMany(Author::class, 'journal_authors', 'journal_id', 'author_id');
    }

    public function getCreatedAtAttribute($date)
    {
        return  Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('Y-m-d');
    }
}

app/Http/Controllers/AuthorsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\AuthorRequest;
use App\Models\Author;
use Illuminate\Http\Request;

class AuthorsController extends Controller
{
    const PAGINATE_DEFAULT = 5;

    public function index()
    {
        $authors = Author::orderBy('id', 'asc')->paginate(self::PAGINATE_DEFAULT);

        return view('authors.index', ['authors' => $authors]);
    }

    public function create()
    {
        return view('authors.create');
    }

    public function store(AuthorRequest $request)
    {
        $credentials = $request->only('lastname', 'firstname', 'secondname');

        (new Author($credentials))->save();

        return redirect()->route('authors');
    }

    public function show(Author $author)
    {
        return view('authors.show', ['author' => $author]);
    }

    public function edit(Author $author)
    {
        return view('authors.edit', ['author' => $author]);
    }

    public function update(AuthorRequest $request,  Author $author)
    {
        $credentials = $request->only('lastname', 'firstname', 'secondname');

        $author->update($credentials);

        return redirect()->route('authors');
    }

    public function delete(Author $author)
    {
        $author->delete();

        return redirect()->route('authors');
    }

    public function journals(Author $author)
    {
        $journals = $author->journals()->get();

        return view('authors.journals', ['author' => $author, 'journals' => $journals]);
    }

    public function fetchData(Request $request)
    {
        if ($request->ajax()) {
            $sortBy     = $request->post('sort_by');
            $sortType   = $request->post('sort_type');

            $authors = Author::orderBy($sortBy, $sortType)->paginate(self::PAGINATE_DEFAULT);

            return view('authors.author_data', ['authors' => $authors])->render();
        }
    }
}

resources/views/authors/author_data.blade.php
@foreach($authors as $author)
    <tr>
        <td>{{ $author->id }}</td>
        <td><a href="{{ route('authors.journals', $author->id) }}" class="text-gray-700 underline">{{ $author->lastname }}</a></td>
        <td>{{ $author->firstname }}</td>
        <td>{{ $author->secondname }}</td>
        <td>
            <div style="display:flex;">
                <a href="{{ route('authors.journals', $author->id) }}" style="padding:5px;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                        <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
                        <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
                    </svg>
                </a>
                <a href="{{ route('authors.edit', $author->id) }}" style="padding:5px;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                        <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
                    </svg>
                </a>
                <form action="{{ route('authors.delete', $author->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-default">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                        </svg>
                    </button>
                </form>
            </div>
        </td>
    </tr>
@endforeach
<tr>
    <td colspan="5">
        {!! $authors->links() !!}
    </td>
</tr>

resources/views/authors/create.blade.php
@extends('layout')

@section('content')
    <div class="d-flex">
        <div class="w-100">
            <h3>Добавление автора</h3>
        </div>
    </div>
    <form action="{{ route('authors.store') }}" method="POST">
        @csrf
        <div class="mb-3 mt-3">
            <label for="lastname" class="form-label">Фамилия</label>
            <input type="text"
                   class="form-control @error('lastname') is-invalid @enderror"
                   id="title"
                   placeholder="Введите фамилию"
                   name="lastname"
                   value="{{ old('lastname') }}"
            />
            @error('lastname')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="mb-3 mt-3">
            <label for="firstname" class="form-label">Имя</label>
            <input type="text"
                   class="form-control @error('firstname') is-invalid @enderror"
                   id="title"
                   placeholder="Введите имя"
                   name="firstname"
                   value="{{ old('firstname') }}"
            />
            @error('firstname')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="mb-3 mt-3">
            <label for="secondname" class="form-label">Отчество</label>
            <input type="text"
                   class="form-control"
                   id="secondname"
                   placeholder="Введите отчество"
                   name="secondname"
                   value="{{ old('secondname') }}"
            />
        </div>
        <button type="submit" class="btn btn-primary">Создать</button>
        <a href="{{ route('authors') }}" class="btn btn-default">Назад</a>
    </form>
@endsection

resources/views/authors/edit.blade.php
@extends('layout')

@section('content')
    <div class="d-flex">
        <div class="w-100">
            <h3>Редактирование автора</h3>
        </div>
    </div>
    <form action="{{ route('authors.update', $author->id) }}" method="POST">
        @csrf
        @method('PATCH')
        <div class="mb-3 mt-3">
            <label for="lastname" class="form-label">Фамилия</label>
            <input type="text"
                   class="form-control @error('lastname') is-invalid @enderror"
                   id="title"
                   placeholder="Введите фамилию"
                   name="lastname"
                   value="{{ $author->lastname }}"
            />
            @error('lastname')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="mb-3 mt-3">
            <label for="firstname" class="form-label">Имя</label>
            <input type="text"
                   class="form-control @error('firstname') is-invalid @enderror"
                   id="title"
                   placeholder="Введите имя"
                   name="firstname"
                   value="{{ $author->firstname }}"
            />
            @error('firstname')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="mb-3 mt-3">
            <label for="secondname" class="form-label">Отчество</label>
            <input type="text"
                   class="form-control"
                   id="secondname"
                   placeholder="Введите отчество"
                   name="secondname"
                   value="{{ $author->secondname }}"
            />
        </div>
        <button type="submit" class="btn btn-primary">Обновить</button>
        <a href="{{ route('authors') }}" class="btn btn-default">Назад</a>
    </form>
@endsection

resources/views/authors/index.blade.php
@extends('layout')

@section('content')
    <div class="container mt-3">
        <h2>Список авторов</h2>
        <a href="{{ route('authors.create') }}" class="btn btn-block btn-primary">Добавить</a>

        @if(!empty($authors) && $authors->count())
            @csrf
            <table class="table table-striped" id="authors-table">
                <thead>
                <tr>
                    <th class="sorting" data-sorting_type="asc" data-column_name="id">№ <span class="px-2" id="id_icon"></span></th>
                    <th class="sorting" data-sorting_type="asc" data-column_name="lastname">Фамилия <span class="px-2" id="lastname_icon"></span></th>
                    <th>Имя</th>
                    <th>Отчество</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                    @include('authors.author_data')
                </tbody>
            </table>
            <input type="hidden" name="hidden_page" id="hidden_page" value="1" />
            <input type="hidden" name="hidden_column_name" id="hidden_column_name" value="id" />
            <input type="hidden" name="hidden_sort_type" id="hidden_sort_type" value="asc" />
        @else
            <p>Данные не найдены</p>
        @endif
    </div>
    <script type="text/javascript">
        $(document).ready(function() {
            function fetchData(page, sort_type, sort_by) {
                $.ajax({
                    headers: {
                        'X-CSRF-TOKEN': $('input[name="_token"]').val()
                    },
                    url: "{{ route('authors.fetch_data') }}",
                    method: 'post',
                    data: {page: page, sort_by: sort_by, sort_type: sort_type},
                    success: function(data) {
                        let _tbody = '#authors-table tbody';

                        $(_tbody).html('');
                        $(_tbody).html(data);
                    }
                });
            }

            $(document).on('click', '.sorting', function(event) {
                event.preventDefault();

                var _columnName = $(this).data('column_name');
                var _orderType = $(this).data('sorting_type');
                var _reverseOrder = '';

                if (_orderType === 'asc') {
                    $(this).data('sorting_type', 'desc');

                    _reverseOrder = 'desc';

                    $('#' + _columnName + '_icon').html('<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-down-square-fill" viewBox="0 0 16 16">\n' +
                        '  <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.5 4.5v5.793l2.146-2.147a.5.5 0 0 1 .708.708l-3 3a.5.5 0 0 1-.708 0l-3-3a.5.5 0 1 1 .708-.708L7.5 10.293V4.5a.5.5 0 0 1 1 0z"/>\n' +
                        '</svg>');
                }

                if (_orderType === 'desc') {
                    $(this).data('sorting_type', 'asc');

                    _reverseOrder = 'asc';

                    $('#' + _columnName + '_icon').html('<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-up-square-fill" viewBox="0 0 16 16">\n' +
                        '  <path d="M2 16a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2zm6.5-4.5V5.707l2.146 2.147a.5.5 0 0 0 .708-.708l-3-3a.5.5 0 0 0-.708 0l-3 3a.5.5 0 1 0 .708.708L7.5 5.707V11.5a.5.5 0 0 0 1 0z"/>\n' +
                        '</svg>');
                }

                $('#hidden_column_name').val(_columnName);
                $('#hidden_sort_type').val(_reverseOrder);

                var _page = $('#hidden_page').val();

                fetchData(_page, _reverseOrder, _columnName);
            });

            $(document).on('click', '.pagination li a.page-link', function(event) {
                event.preventDefault();

                var _page = $(this).attr('href').split('page=')[1];
                $('#hidden_page').val(_page);

                var _columnName = $('#hidden_column_name').val();
                var _sortType = $('#hidden_sort_type').val();

                fetchData(_page, _sortType, _columnName);
            });
        });
    </script>
@endsection
<style>
    .sorting {cursor:default;}
</style>

resources/views/authors/journals.blade.php
@extends('layout')

@section('content')
    <div class="container mt-3">
        <div class="d-flex">
            <div class="w-100">
                <h2>Список журналов - {{ $author->lastname }} {{ $author->firstname }}</h2>
            </div>
            <div class="flex-shrink-1">
                <a href="{{ route('authors') }}" class="text-md text-gray-700 underline px-4">Назад</a>
            </div>
        </div>
        @if(!empty($journals) && $journals->count())
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>№</th>
                    <th>Название</th>
                    <th>Короткое описание</th>
                    <th>Картинка</th>
                    <th>Авторы</th>
                    <th>Дата выпуска</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach($journals as $journal)
                    <tr>
                        <td>{{ $journal->id }}</td>
                        <td>{{ $journal->title }}</td>
                        <td>{{ $journal->description }}</td>
                        <td>
                            @if (isset($journal->images->first()->path) )
                                <img src="{{ url('storage/' . $journal->images->first()->path) }}" class="img-fluid img-thumbnail w-25 p-3" style="width:50px;" />
                            @else
                                -
                            @endif
                        </td>
                        <td>
                            @foreach($journal->authors as $author)
                                <p>{{ $author->lastname }} {{ $author->firstname }}</p>
                            @endforeach
                        </td>
                        <td>{{ $journal->created_at }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        @else
            <p>Данные не найдены</p>
        @endif
    </div>
@endsection

resources/views/authors/show.blade.php
@extends('layout')

@section('content')
    <table class="table">
        <tbody>
            <tr>
                <th scope="row">Фамилия</th><td>{{ $author->lastname }}</td>
            </tr>
            <tr>
                <th scope="row">Имя</th><td>{{ $author->firstname }}</td>
            </tr>
            <tr>
                <th scope="row">Отчество</th><td>{{ $author->secondname }}</td>
            </tr>
        </tbody>
    </table>
@endsection